#%%
import pandas as pd
import numpy as np
import os

# get the directory of the file
dir_path = os.path.dirname(os.path.abspath(__file__))
os.chdir(dir_path)

# load the features without energies (generated by Stephen in tools directory)
df_no_energies = pd.read_csv('without_energies_test_set_features.csv', index_col=0)

# load the energies (generated by Sam in energies_from_ambertools directory)
df_energies = pd.read_csv('energies_test_set.csv', index_col=0)

# combine the two dataframes
df = pd.concat([df_no_energies, df_energies], axis=1)

print(df.index)
# add ".pdb" to the end of the index
df.index = [f'{index}.pdb' for index  in df.index]

#%% Save the combined dataframe
df.to_csv('test_set_features.csv',index=True)

# %%
